apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: hcloud
  namespace: kube-system
spec:
  encryptedData:
    token: AgCRzSZmKODxcSpe6YcYDJ8LylPaLF6uoIVpXEg7h/kSdHuLmffumrRC4m0AIZ6UWC4f5nZTX353oUePh+6ErcikaLaOTDO1vH2pNsMcdodkOP7FAh4KRdR/cINMtyAJcPOuSwd4fIk/vQcM8FtGIYIdyDKr12U1K+TdcjqEUJanYoKlpBzEcw4UevdFg+4jlIvb724yQmlRzAeqs7r6yxQwkQmlOHAnpDJz+r+6WCl+xr1Z4Deio0vAGMEtgCILKNGf9ctU7EEycBkl4kaxnH+4MWPgl64zUXwQH6ccsY+OIEwJYIh1ZIokUJ6o1wfT3urLdQvkWM6yt0a0qZV3UZ4pMNNKCNteNesZz4l7sZBVBrTpJLeQm8K6Kq1IRysQFWIcsWEoDHTw/9hHx+zOzM41x1b7d7yEDryr1sBVkt0QUK+tlL5Z0TnJiPYr2QRSozqtjkZ8wYb3wflABdeVJC6p8pkE1phnXBKkgfu6L+I3u9mgmRagRbVYSG1l7DEMP6kALro7ghx6g1V5+vYMLrPz6FOEx44a8oh3D8JvUa9dvaZZG93t4MUVkR/SQZuZqGYsErYOY6Poh+WxC7htPhke1jLNM3J2QTrult7lm7kkcS1OqVG5MoA84CN94mToz/19iTwLnowd9YuJHesASx39KaW5TtuAfyuguaMg7jus+4bLQyL+8eGfE2bpFdrkMWruM/aSnOydPfw+c5CmWFLM6a+Go5HaIGF8SbR6+YUIWMfkQHXxCTMccZNpy7Zf20KlLLbrYluyXBiFbVjDlsTKlQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: hcloud
      namespace: kube-system

