apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: hcloud-csi
  namespace: kube-system
spec:
  encryptedData:
    token: AgA2H1heGMHVlaYjEPw/rqc5l6pE3Gq4xzFyVPCAxhbeiCHXErGUYpZ6P1xha1yCDMwM8x4i1phf4/Qhk15XbwRjbf7yzjOXNivAiaPBn9s5+iFdy6/XiXNOOT6pTCclPGolCjE6iQq0S6imuAkWuk4nOo295NtUGDq+6h66yAIROKhvFq5TQFDH7L6A6hCdH3LBv2MYf/1PT/IwwY/q+0+Sm/sYGgTA0mzLe1m2BbkjOsrYg8WsUeJsqwwpQwQQQmKeaimjxmNamdtMQbJCVWYzEMbcwyifYX8UpY7OQJT5w/HeYuIDNxHQCTr7dfUL83DX9TzrgAOzb42GrCew0X65/ESx7C4cXfjLlgTx+ou48ehtYKol0voVJl2TeJ5UlkpjkoCLSjqEooBG/sWAUvvUJru4nlK0jsSMkTWJGQEe1zR/VCIU8NeolO4wFuOd5Jrs233rY5JPlFFlTlx/5IvWAnRYVTmxZE2sqZ52bflPIU9Hm6vqGH8B+A8zZvD313B4g4gRM/5vF5Lg53cPFS79Ih27dajSiGd1xRXCdprD04TBtjZJ4de2YtG2mmaY8GmEL5vuw7V8dBFHnM8S4sJXkYWUxwhoIQ2d0t/+VeQpNHyEdruVLt7YR5OCYs0MNtjEMWcaMVTB2LNGurVTR0PCGdYBC9ERyo6GEg5s5L/YZtudJGyiHtc1fCzfji9cT+tXWFNeU+B7Az6vrM38HS9DXUQIFdebhx+nr1W8/AFHCG8KE3YiVbsbaxsZeIwxgYg2C+/OeNRMsIvlb/VjrEasKA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: hcloud-csi
      namespace: kube-system

