apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: hcloud
  namespace: kube-system
spec:
  encryptedData:
    token: AgCNQknzND9m/dZjyKLESnxcCcNdnFmsaU7Tt6H0utTi4j/aNeGGEpLf1T/devxSYczU1CAa2zFUvPB0mPYDg5tWRQ317WljpVOTYGleIFtYZHcwV2S5rcUK1cnQ1dNiMpyLkrxU91TneD95se76pMdRI9/sfo6IP3jydh9TpThqCsQsQNF0tPlNju14fnaE8kxfe7huFmfz/RiwOYjzh5ZWXeWUK2FGu9Q7+I+Q2g3EYxue3/UkS7U4yKiXWYhLVHuK9ydJSL8RqgTrV2YVXZSjI/d9mdESzOJFrftWwM5GXvU6Wlzk/5gWwMdkjTVB/x/dt8miFEa+cZXBk/vImArnib2rA9/WkZyE2WlUrGeLMiQWUid10IrAN9G93wc6AIR9tOsTZwSFnF891/VHjurVLuPULcdyx8mb1aUZ8LxsZ0ka5+4XXMekBVRyXpqTV6CCt6TMHkBRsD++7YZZKHuqa/oQKr2jf8DDZ3BoSEuLYRwSivZMp6cOloo2WfPf/TGJEYNpdOFhTJoYsvJRz550aGToRzwezVh+M4ntgvadILC+3OSxmaAV65r6rYvzA76ivys8cR5X3Lp+ebyk9ExbGeFdtgRXqbEyX8DHQ97qyOK/Ff6TGSvcZczxE6X/EAGDDtypSPf1cKHRoc8Xl7ABNsHi23k4L/fmlqDZeq/3E92+uH/D9OfB8wxJXWvhUp4U2LZTmkbT7feWlwyNOlheUjLk1kTTMtg/o9H0/P6uT8tIgsnNwZI2/GvZX/+AMM1rXFdBAOmaUZ9Y9WFbodrD5w==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: hcloud
      namespace: kube-system

