apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: hcloud-csi
  namespace: kube-system
spec:
  encryptedData:
    token: AgBfYOQ8M7sqR0dbGr4MUh1Z53/+7eEsy+wksn/JZ0GMsbWAY0VR4f5L0JPJfgcsuszduhttgLvAaI/QNFIUFn85vwiGSN8hZ8yVtjZYWaCg+87WkT6i7NyYyB/q6G0PDOL343sSLW4grHTKGWZhT1xWu3nFyq/pG7Uc0/XrIIBEPrSBnHcuOBhSqHuYwWWzNfHYHvAxyq89dv/mhYnzsh1czSpuNowHsmJfzKCX8RLLgMWHdGAT9qTvd83F+mq/Oa0QZYoH/E01oqYmPpDOb48OKXIkao9KOQvUIDPYUvfmJkDVtL8eeZLCA0cbQndxRQUD+r6GEZDLbEtIeQkdCBFXnC3DifiuSeLbnwOkKfMOGerHcw0FqJhp17chYpCtS91FrtNQXITOAj9rXEHFcQNjFwLJnb43AOKZJoVD9LHeBnMy8sOASB0wnvQ4W+mIsD7sGcl9ignNh6auDAVRJ40uIZI2uAXmMpgNaENma/yT1X62plETihVxJJRcX9qvOsfmbap7JEJ1PmSb6VdlEGez9jybtMuGxFPZt2ZJbAdvBWqCoCy0uhrznPB8d2c+CqAWH+dh62wocrrZflcQiIVF8kgvUzi8anA8qUfoQlLJ1GMXVYQD4BfbnQ5CZJnkVn66wTuig/YZHd3SQahGZuJU0Rys7D5J2aWU4c2kbMCIzm/eC+1Qt7l7SoH5nWFLBsu3v0GzUAUuDMYxzsi9WhJ5VknoofFZd9XlTvINe8RGg9/4A5d3KYqBJyrDiuc1nSYrSi3K88bHbTAnYMQz0qeJ
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: hcloud-csi
      namespace: kube-system

