apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: hcloud-csi
  namespace: kube-system
spec:
  encryptedData:
    token: AgBLjgrLqv52nuDSFN729QkJYb1fB/Z8yF4X/L5N08rcgLUwOEtrrhTs1uIXSrIBJq2IMNKPktDsAUBwOJkqmfdSDriZx6fSnRbF3z6EbaRN86N3ysGohWcTnwEGLhtpA7TYMCmEY98Db9vQIRRW24pP8+gmrexpdSoEAOVmF1indwbZM6XUZV5U9nb5ReDzLamQGfWonwmMbUYY9yHaUKp7pvzZMIopp+dd1msqS03q3W2EkS7h5ceW6pBsm0/V3ygrT+SKRB3AAScj1zNMerlVpMcsdppvZez7sfVNgUFzJE7vh+nSdLt2U7pABI2AuRmMdqFEMj0tQ9Nk1IUj382eQxOjvBlw1uSfdOpKDl8znCrAcEvf8HIKpsw8qP9hW2vFA3gNE8w4cwZ9EbWga0SJZuMDmQZiWOIwbedzzjlHsL+/WCzBxLd1OGXor3krq344vTPqq2UDEpTi1Jb/lX+cJAV2EAii7H99zRRrCHb9tWjOZjNcORkoAEAuLYJchwOyRfMVzLEQL+bEUVoBCzchaHXq7IcthHCnuvUVp1A6CTClOeSEGDgsv9gEuSaKuHDQjLIWiyw3jPXR/aM1a/MljH4WdXVSy9eoJpvK+oxjv0ZvypFbYfwTVswcNMd14GOnp3TdqrW9oS/1+EkXInCyakz0yCFA/YGYWdJ65OkLL5du6KBbElPLinl3XZprHausAOfmeo9Uqn0X+/LhAEbgD+MQs9cV4vz92hg5qc/olDeOqrptkuRIpAAMG9wjQ0f/bBI0oYSlTfhjKEeUwhql7g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: hcloud-csi
      namespace: kube-system

