apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: hcloud
  namespace: kube-system
spec:
  encryptedData:
    token: AgA6gPoziR2gP6qQWuB5RxrQtKWQRSomGHo2YZh/1MNyzZVojWpN9T93zEfgJDh+nE9pQKQtyMJ9kHo/GOYN0nMU3WC1o1Nd3VBkoh7ypAwtkhRAnWeNuD5W3df5bevF4tee8cNV0Xy/C7bUWhkM+xeW/2bBX/vhs91phJlDCxv7thmYEvPRy2CF5m/3pH5BLxlw6ch1q2rXy0BvR9XIOZTjGTEh1RUhL+lSUxOPZLMT0Feza/BqT9EoyKk0ARaB+2ixeVHqN8z8b9ygRLwKa7Mrd6oaVArZ4V912tX44k5NJHT4C85h8VJUouf+P8sqU/fcBtY4667DYqKhQqq93LM4/IvE6vaz5QA9HebSj7xr3Jc3svOs0mm28FvF3W6e9e5QXJ/nnaFK+AbvnrEz5KXe257smgo3Ml1eS3AdnqndQezfepM9cUG84fBxNjygsDmubZJ9J+eT4AfLExCKyuhnDOAnImBv3ZfXIpEyPmNr4kUfV1OXpZuslvZTUomdtOsB5mZ3e2EoxCB5f0jO2bisu5NijRNjWr2wMr7xRm7syXB3pbUjqhAAp2w1VM2RxmFlSHZKe5sMjpDiGQCfw1UGgVlmpWNkubUepdCpFukhESFDd+VlhMovGcOZeBwjhVpcCh0uIUwsKPgw/bQAN5pMDY0pO5LzS3QLMmug+cJyiXFy3jpQUZvctaFtaCbSV18leeyI22sbSq7QskLfrqwpQrVZFvPD1Wwd2c3G1f7LeztfoknNVSBn/iKbWyu99spna4X+bcOBl0TsTTn4UmX5KA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: hcloud
      namespace: kube-system

