---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debugsecrets
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: debugsecrets
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: debugsecrets
      annotations:
        prometheus.io/scrape: "true"
    spec:
      tolerations:
        # this taint is set by all kubelets running `--cloud-provider=external`
        # so we should tolerate it to schedule the helm operator
        - key: "node.cloudprovider.kubernetes.io/uninitialized"
          value: "true"
          effect: "NoSchedule"
      containers:
        - name: debug-secret
          image: nginx
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
          env:
            - name: HCLOUD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hcloud
                  key: token
          
