apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: grafana
  namespace: infrastructure
spec:
  releaseName: grafana
  chart:
    repository: https://grafana.github.io/helm-charts
    name: grafana
    version: 6.7.2
  values:
    sidecar:
      datasources:
        enabled: true
      dashboards:
        enabled: true
      notifiers:
        enabled: true
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt
      tls:
        - secretName: tls-grafana
          hosts:
            - grafana.trec.ch
      hosts:
        - grafana.trec.ch
      path: /
