apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: loki
  namespace: infrastructure
spec:
  releaseName: loki
  chart:
    repository: https://grafana.github.io/helm-charts
    name: loki-stack
    version: 2.3.1
  values:
    grafana:
      enabled: false
    prometheus:
      enabled: false
