apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: infrastructure
spec:
  releaseName: sealed-secrets-controller
  chart:
    repository: https://bitnami-labs.github.io/sealed-secrets
    name: sealed-secrets
    version: 1.15.0-r3
  values:
    tolerations:
      # this taint is set by all kubelets running `--cloud-provider=external`
      # so we should tolerate it to schedule sealed-secrets
      - key: "node.cloudprovider.kubernetes.io/uninitialized"
        value: "true"
        effect: "NoSchedule"
